package com.tapmahjong.engine

import kotlin.math.abs
import kotlin.random.Random

/**
 * Mahjong solitaire tile set + board rules.
 *
 * Faces 0..41 (42 distinct):
 *   0..8   dots 1-9      9..17  bamboo 1-9     18..26 characters 1-9
 *   27..30 winds E S W N 31..33 dragons R G W
 *   34..37 flowers       38..41 seasons
 * Two tiles match when they're identical — except any flower matches any
 * flower and any season matches any season (matchKey collapses those groups).
 *
 * A tile is FREE (selectable) when nothing sits on top of it and at least one
 * of its left/right sides is open. Deals are generated by reverse-solving so
 * every deal has at least one solution.
 */
data class Slot(val layer: Int, val gx: Int, val gy: Int)

object Faces {
    const val COUNT = 42
    fun matchKey(face: Int) = when (face) {
        in 34..37 -> 100   // all flowers
        in 38..41 -> 101   // all seasons
        else -> face
    }
}

class Board(val slots: List<Slot>) {
    val n = slots.size
    val face = IntArray(n) { -1 }
    val present = BooleanArray(n) { true }

    fun clone(): Board {
        val b = Board(slots)
        System.arraycopy(face, 0, b.face, 0, n)
        System.arraycopy(present, 0, b.present, 0, n)
        return b
    }

    fun remaining(): Int { var c = 0; for (i in 0 until n) if (present[i]) c++; return c }

    private fun onTop(a: Slot, b: Slot) = abs(a.gx - b.gx) <= 1 && abs(a.gy - b.gy) <= 1

    fun isFree(i: Int, pres: BooleanArray = present): Boolean {
        if (!pres[i]) return false
        val s = slots[i]
        var left = false; var right = false
        for (j in 0 until n) {
            if (!pres[j] || j == i) continue
            val o = slots[j]
            if (o.layer == s.layer + 1 && onTop(s, o)) return false
            if (o.layer == s.layer && abs(s.gy - o.gy) <= 1) {
                if (o.gx == s.gx - 2) left = true
                if (o.gx == s.gx + 2) right = true
            }
        }
        return !(left && right)
    }

    fun freeSlots(): List<Int> = (0 until n).filter { isFree(it) }

    fun canMatch(a: Int, b: Int) =
        a != b && present[a] && present[b] && isFree(a) && isFree(b) &&
            Faces.matchKey(face[a]) == Faces.matchKey(face[b])

    /** A free, matchable pair if one exists (for hints and stuck-detection). */
    fun findMatch(): Pair<Int, Int>? {
        val free = freeSlots()
        for (x in free.indices) for (y in x + 1 until free.size) {
            val a = free[x]; val b = free[y]
            if (Faces.matchKey(face[a]) == Faces.matchKey(face[b])) return a to b
        }
        return null
    }

    fun hasMove() = findMatch() != null

    fun remove(a: Int, b: Int) { present[a] = false; present[b] = false }
    fun restore(a: Int, b: Int) { present[a] = true; present[b] = true }

    /** Why a present tile isn't selectable. */
    fun explainTile(i: Int): String {
        val s = slots[i]
        for (j in 0 until n) {
            if (present[j] && slots[j].layer == s.layer + 1 && onTop(s, slots[j]))
                return "A tile is resting on top of that one."
        }
        return "That tile is blocked on both sides — clear a neighbor first."
    }

    // ------------------------------------------------- solvable dealing

    /** Assign faces so the layout is solvable (reverse removal of free pairs). */
    fun deal(rng: Random): Boolean {
        val pairs = buildPairs(n / 2, rng)
        return assignSolvable(pairs, rng)
    }

    /** Reshuffle the currently-present tiles, keeping the same multiset, solvable. */
    fun reshuffle(rng: Random): Boolean {
        val liveSlots = (0 until n).filter { present[it] }
        val pairs = pairsFromFaces(liveSlots.map { face[it] })
        return assignSolvable(pairs, rng, liveSlots)
    }

    private fun assignSolvable(
        pairs: List<Pair<Int, Int>>, rng: Random,
        liveSlots: List<Int> = (0 until n).toList(),
    ): Boolean {
        repeat(400) {
            val pres = BooleanArray(n) { false }
            for (s in liveSlots) pres[s] = true
            val assigned = IntArray(n) { -1 }
            val bag = pairs.shuffled(rng)
            var ok = true
            for ((fa, fb) in bag) {
                val open = liveSlots.filter { pres[it] && isFree(it, pres) }
                if (open.size < 2) { ok = false; break }
                val s1 = open.random(rng)
                val s2 = open.filter { it != s1 }.random(rng)
                assigned[s1] = fa; assigned[s2] = fb
                pres[s1] = false; pres[s2] = false
            }
            if (ok) {
                for (s in liveSlots) face[s] = assigned[s]
                return true
            }
        }
        return false
    }

    companion object {
        /** Matched face pairs from the standard set, trimmed to `count` pairs. */
        private fun buildPairs(count: Int, rng: Random): List<Pair<Int, Int>> {
            val all = ArrayList<Pair<Int, Int>>(72)
            for (f in 0..33) { all.add(f to f); all.add(f to f) } // 4 of each honor/suit
            all.add(34 to 35); all.add(36 to 37)                  // flowers
            all.add(38 to 39); all.add(40 to 41)                  // seasons
            all.shuffle(rng)
            return all.take(count)
        }

        private fun pairsFromFaces(faces: List<Int>): List<Pair<Int, Int>> {
            val byKey = HashMap<Int, ArrayList<Int>>()
            for (f in faces) byKey.getOrPut(Faces.matchKey(f)) { ArrayList() }.add(f)
            val out = ArrayList<Pair<Int, Int>>(faces.size / 2)
            for (group in byKey.values) {
                var k = 0
                while (k + 1 < group.size) { out.add(group[k] to group[k + 1]); k += 2 }
            }
            return out
        }
    }
}
